import type { LearningModule, Lesson, LessonSkillTag, LocalizedSupport } from "@/src/types/content";

type SupportPair = {
  hiDeva: string;
  hiLatn: string;
};

type SentenceSpec = SupportPair & {
  text: string;
  notes?: SupportPair;
};

type AdvancedLessonSpec = {
  id: string;
  moduleId: string;
  title: string;
  overview: string;
  skipOverview: string[];
  main: SentenceSpec;
  support: SentenceSpec;
  keyPhrase: string;
  keyOptions: [string, string, string];
  keyExplanation: SupportPair;
  incorrect: string;
  wrong: string;
  speak: SentenceSpec;
  tags: LessonSkillTag[];
};

function localized({ hiDeva, hiLatn }: SupportPair): LocalizedSupport {
  return {
    "hi-Deva": hiDeva,
    "hi-Latn": hiLatn,
  };
}

function createSentence(lessonId: string, suffix: string, sentence: SentenceSpec) {
  return {
    id: `${lessonId}-${suffix}`,
    targetLanguage: "en-IN" as const,
    targetText: sentence.text,
    support: localized(sentence),
    ...(sentence.notes ? { notes: localized(sentence.notes) } : {}),
  };
}

function splitAroundPhrase(text: string, phrase: string) {
  const index = text.indexOf(phrase);
  if (index < 0) {
    return { start: `${text} `, end: "" };
  }

  if (index === 0) {
    return {
      start: "Begin with ",
      end: text.slice(phrase.length),
    };
  }

  return {
    start: text.slice(0, index),
    end: text.slice(index + phrase.length),
  };
}

function sentenceWords(sentence: string) {
  return sentence.split(/\s+/).filter(Boolean);
}

function createAdvancedLesson(spec: AdvancedLessonSpec): Lesson {
  const mainSentence = createSentence(spec.id, "main", spec.main);
  const supportSentence = createSentence(spec.id, "support", spec.support);
  const speakSentence = createSentence(spec.id, "speak", spec.speak);
  const fill = splitAroundPhrase(spec.main.text, spec.keyPhrase);

  return {
    id: spec.id,
    moduleId: spec.moduleId,
    title: spec.title,
    durationMinutes: 11,
    overview: spec.overview,
    skipOverview: spec.skipOverview,
    activities: [
      {
        type: "sentence",
        prompt: "Study the main sentence and notice how the ideas are connected.",
        sentence: mainSentence,
      },
      {
        type: "sentence",
        prompt: "Add one supporting sentence so the conversation sounds complete.",
        sentence: supportSentence,
      },
      {
        type: "chooseMeaning",
        prompt: "Choose the meaning of the main sentence.",
        sentence: mainSentence,
        options: [spec.main.hiDeva, "मुझे अभी चाय बनानी है।", "बच्चे ने खेलना शुरू किया।"],
        answer: spec.main.hiDeva,
        explanation: localized({
          hiDeva: "यह option पूरे English sentence का सही अर्थ बताता है।",
          hiLatn: "Yeh option poore English sentence ka sahi meaning batata hai.",
        }),
      },
      {
        type: "fillBlank",
        prompt: "Choose the phrase that connects the sentence naturally.",
        sentenceStart: fill.start,
        sentenceEnd: fill.end,
        options: spec.keyOptions,
        answer: spec.keyPhrase,
        explanation: localized(spec.keyExplanation),
      },
      {
        type: "choice",
        prompt: "Which sentence sounds natural and complete?",
        options: [spec.main.text, spec.incorrect, spec.wrong],
        answer: spec.main.text,
        explanation: localized({
          hiDeva: "Natural English में idea, reason, और request साफ order में आते हैं।",
          hiLatn: "Natural English mein idea, reason, aur request clear order mein aate hain.",
        }),
      },
      {
        type: "fixSentence",
        prompt: "Fix the sentence so it sounds confident and respectful.",
        incorrectSentence: spec.incorrect,
        options: [spec.main.text, spec.incorrect, spec.wrong],
        answer: spec.main.text,
        explanation: localized({
          hiDeva: "Correct sentence में grammar के साथ tone भी polite और clear है।",
          hiLatn: "Correct sentence mein grammar ke saath tone bhi polite aur clear hai.",
        }),
      },
      {
        type: "arrangeWords",
        prompt: "Arrange the words into a useful spoken sentence.",
        words: sentenceWords(spec.speak.text),
        answer: sentenceWords(spec.speak.text),
        explanation: localized({
          hiDeva: "Short practice sentence को calm rhythm में बोलना आसान होता है।",
          hiLatn: "Short practice sentence ko calm rhythm mein bolna easy hota hai.",
        }),
      },
      {
        type: "speak",
        prompt: "Say the sentence in your own steady Indian English voice.",
        sentence: speakSentence,
      },
    ],
  };
}

export const advancedModules: LearningModule[] = [
  {
    id: "advanced-home-decisions",
    title: "Advanced Home Decisions",
    level: "Conversational",
    stage: 18,
    skillFocus: "Discuss sensitive home decisions with reasons, boundaries, and calm confidence.",
    challenge: "Balance directness and respect in longer family conversations.",
    overview: "Practice mature household conversations about priorities, budgets, boundaries, and fairness.",
    lessonIds: [
      "discuss-renovation-priorities",
      "explain-household-boundaries",
      "negotiate-family-expectations",
      "discuss-shared-budget-plan",
      "respond-to-unfair-comment",
    ],
  },
  {
    id: "healthcare-advocacy",
    title: "Healthcare Advocacy",
    level: "Conversational",
    stage: 19,
    skillFocus: "Explain health patterns, ask careful questions, and speak up for care needs.",
    challenge: "Use detail without sounding confused or aggressive.",
    overview: "Practice advanced clinic and family-care conversations where clarity matters.",
    lessonIds: [
      "explain-recurring-symptom-pattern",
      "ask-for-second-opinion",
      "discuss-caregiver-burnout",
      "clarify-test-report",
      "describe-medicine-side-effect",
    ],
  },
  {
    id: "work-skills-income",
    title: "Work, Skills, And Income",
    level: "Conversational",
    stage: 20,
    skillFocus: "Talk about skills, flexible work, home business, and customer issues.",
    challenge: "Sound confident while explaining experience and constraints.",
    overview: "Build speaking confidence for earning opportunities, interviews, and small-business conversations.",
    lessonIds: [
      "describe-home-business-idea",
      "explain-work-gap-confidently",
      "discuss-flexible-work-need",
      "handle-customer-complaint",
      "present-skill-achievement",
    ],
  },
  {
    id: "education-advocacy",
    title: "Education Advocacy",
    level: "Conversational",
    stage: 21,
    skillFocus: "Discuss learning needs, school action plans, and child wellbeing.",
    challenge: "Ask focused questions and request next steps clearly.",
    overview: "Practice deeper parent-school conversations with practical follow-up.",
    lessonIds: [
      "discuss-learning-difficulty",
      "request-parent-teacher-action-plan",
      "explain-child-emotional-change",
      "ask-about-exam-preparation",
      "discuss-digital-safety-with-school",
    ],
  },
  {
    id: "civic-and-services",
    title: "Civic And Services",
    level: "Conversational Plus",
    stage: 22,
    skillFocus: "Follow up on official complaints, timelines, and unresolved service issues.",
    challenge: "Stay firm, factual, and polite over multiple turns.",
    overview: "Practice English for formal service follow-up, civic issues, and escalation.",
    lessonIds: [
      "file-formal-service-complaint",
      "follow-up-government-office",
      "explain-neighborhood-safety-pattern",
      "request-clear-timeline",
      "escalate-unresolved-issue",
    ],
  },
  {
    id: "financial-confidence",
    title: "Financial Confidence",
    level: "Conversational Plus",
    stage: 23,
    skillFocus: "Ask careful money questions and explain financial choices.",
    challenge: "Compare options, refuse pressure, and request clarity.",
    overview: "Practice English for loans, insurance, savings, charges, and financial boundaries.",
    lessonIds: [
      "compare-loan-options",
      "ask-about-hidden-charges",
      "explain-savings-goal",
      "discuss-insurance-claim",
      "refuse-unnecessary-purchase",
    ],
  },
  {
    id: "conflict-and-boundaries",
    title: "Conflict And Boundaries",
    level: "Conversational Plus",
    stage: 24,
    skillFocus: "Handle pressure, disagreement, and misunderstandings with calm boundaries.",
    challenge: "Use respectful but firm English in emotional conversations.",
    overview: "Practice saying no, disagreeing, repairing misunderstandings, and asking for support.",
    lessonIds: [
      "respond-to-pressure-politely",
      "disagree-with-family-respectfully",
      "set-time-boundary",
      "repair-misunderstanding",
      "express-need-without-blame",
    ],
  },
  {
    id: "storytelling-and-opinions",
    title: "Storytelling And Opinions",
    level: "Fluent Practice",
    stage: 25,
    skillFocus: "Tell personal stories and explain opinions with balance.",
    challenge: "Connect past, present, reasons, and reflection naturally.",
    overview: "Move into expressive English for stories, opinions, proud moments, and comparisons.",
    lessonIds: [
      "narrate-challenge-and-solution",
      "explain-why-opinion-changed",
      "compare-past-and-present",
      "describe-proud-moment",
      "give-balanced-opinion",
    ],
  },
  {
    id: "public-speaking-and-groups",
    title: "Public Speaking And Groups",
    level: "Fluent Practice",
    stage: 26,
    skillFocus: "Speak in small groups with structure, support, and closure.",
    challenge: "Organize your point while acknowledging other people.",
    overview: "Practice group discussion English for meetings, committees, and community decisions.",
    lessonIds: [
      "introduce-topic-in-meeting",
      "support-someone-else-point",
      "ask-group-to-decide",
      "summarize-mixed-opinions",
      "close-group-discussion",
    ],
  },
  {
    id: "advanced-fluency-mix",
    title: "Advanced Fluency Mix",
    level: "Fluent Practice",
    stage: 27,
    skillFocus: "Handle complex, multi-step conversations with confidence.",
    challenge: "Use conditions, sequence, clarification, and reflection in one flow.",
    overview: "Practice the most advanced everyday speaking patterns in the current curriculum.",
    lessonIds: [
      "handle-difficult-phone-negotiation",
      "explain-complicated-sequence",
      "make-conditional-request",
      "clarify-before-committing",
      "reflect-on-learning-progress",
    ],
  },
];

const advancedLessonSpecs: AdvancedLessonSpec[] = [
  {
    id: "discuss-renovation-priorities",
    moduleId: "advanced-home-decisions",
    title: "Discuss Renovation Priorities",
    overview: "You will practice comparing repair priorities when money and time are limited.",
    skipOverview: ["Naming the urgent repair", "Comparing it with a nice-to-have change", "Suggesting a timeline"],
    main: {
      text: "Although the kitchen tiles look old, repairing the leaking pipe should be our first priority.",
      hiDeva: "Kitchen tiles पुराने लगते हैं, फिर भी leaking pipe repair करना हमारी पहली priority होनी चाहिए।",
      hiLatn: "Kitchen tiles purane lagte hain, phir bhi leaking pipe repair karna hamari pehli priority honi chahiye.",
    },
    support: {
      text: "We can plan the cosmetic work after the urgent repair is finished.",
      hiDeva: "Urgent repair पूरा होने के बाद हम cosmetic work plan कर सकते हैं।",
      hiLatn: "Urgent repair poora hone ke baad hum cosmetic work plan kar sakte hain.",
    },
    keyPhrase: "Although",
    keyOptions: ["Although", "Because", "Until"],
    keyExplanation: {
      hiDeva: "'Although' दिखाता है कि एक बात सच है, लेकिन priority दूसरी है।",
      hiLatn: "'Although' dikhata hai ki ek baat sach hai, lekin priority doosri hai.",
    },
    incorrect: "Kitchen tiles old but leaking pipe first priority should.",
    wrong: "Repairing leaking pipe should old kitchen tiles priority although.",
    speak: {
      text: "The leaking pipe should be our first priority.",
      hiDeva: "Leaking pipe हमारी पहली priority होनी चाहिए।",
      hiLatn: "Leaking pipe hamari pehli priority honi chahiye.",
    },
    tags: ["contrast-connector", "planning", "decision-discussion", "home-request"],
  },
  {
    id: "explain-household-boundaries",
    moduleId: "advanced-home-decisions",
    title: "Explain Household Boundaries",
    overview: "You will practice saying what you can and cannot manage without sounding rude.",
    skipOverview: ["Stating your limit", "Offering another option", "Keeping the tone respectful"],
    main: {
      text: "I can help with the guests, but I cannot take responsibility for every arrangement alone.",
      hiDeva: "मैं guests में help कर सकती हूँ, लेकिन हर arrangement की responsibility अकेले नहीं ले सकती।",
      hiLatn: "Main guests mein help kar sakti hoon, lekin har arrangement ki responsibility akele nahi le sakti.",
    },
    support: {
      text: "If we divide the work, everything will be easier for everyone.",
      hiDeva: "अगर हम काम बाँट लें, तो सबके लिए आसान रहेगा।",
      hiLatn: "Agar hum kaam baant lein, to sabke liye easy rahega.",
    },
    keyPhrase: "but",
    keyOptions: ["but", "because", "after"],
    keyExplanation: {
      hiDeva: "'But' help और boundary को एक sentence में balance करता है।",
      hiLatn: "'But' help aur boundary ko ek sentence mein balance karta hai.",
    },
    incorrect: "I help guests but cannot responsibility every arrangement alone.",
    wrong: "I can help guests but every arrangement alone responsibility cannot.",
    speak: {
      text: "I cannot take responsibility for every arrangement alone.",
      hiDeva: "मैं हर arrangement की responsibility अकेले नहीं ले सकती।",
      hiLatn: "Main har arrangement ki responsibility akele nahi le sakti.",
    },
    tags: ["polite-disagreement", "family", "confidence", "decision-discussion"],
  },
  {
    id: "negotiate-family-expectations",
    moduleId: "advanced-home-decisions",
    title: "Negotiate Family Expectations",
    overview: "You will practice discussing expectations before they become pressure.",
    skipOverview: ["Acknowledging the expectation", "Explaining the constraint", "Suggesting a fair plan"],
    main: {
      text: "I understand that everyone wants a big celebration, but we should choose a plan that we can manage peacefully.",
      hiDeva: "मैं समझती हूँ कि सब बड़ा celebration चाहते हैं, लेकिन हमें ऐसा plan चुनना चाहिए जिसे हम peacefully manage कर सकें।",
      hiLatn: "Main samajhti hoon ki sab bada celebration chahte hain, lekin humein aisa plan chunna chahiye jise hum peacefully manage kar saken.",
    },
    support: {
      text: "A smaller gathering may feel warmer and less stressful.",
      hiDeva: "छोटी gathering ज़्यादा warm और कम stressful लग सकती है।",
      hiLatn: "Chhoti gathering zyada warm aur kam stressful lag sakti hai.",
    },
    keyPhrase: "that",
    keyOptions: ["that", "than", "then"],
    keyExplanation: {
      hiDeva: "'I understand that...' सामने वाले की बात acknowledge करने का polite तरीका है।",
      hiLatn: "'I understand that...' saamne wale ki baat acknowledge karne ka polite tareeka hai.",
    },
    incorrect: "I understand everyone wants big celebration but we choose manageable peacefully plan.",
    wrong: "Everyone wants big celebration that understand I but peaceful manage plan.",
    speak: {
      text: "We should choose a plan that we can manage peacefully.",
      hiDeva: "हमें ऐसा plan चुनना चाहिए जिसे हम peacefully manage कर सकें।",
      hiLatn: "Humein aisa plan chunna chahiye jise hum peacefully manage kar saken.",
    },
    tags: ["family", "planning", "polite-disagreement", "reason-connector"],
  },
  {
    id: "discuss-shared-budget-plan",
    moduleId: "advanced-home-decisions",
    title: "Discuss A Shared Budget Plan",
    overview: "You will practice explaining how a shared budget can reduce confusion.",
    skipOverview: ["Naming the money issue", "Suggesting shared tracking", "Explaining the benefit"],
    main: {
      text: "If we track the monthly expenses together, we can avoid confusion about where the money is going.",
      hiDeva: "अगर हम monthly expenses साथ में track करें, तो money कहाँ जा रहा है इस confusion से बच सकते हैं।",
      hiLatn: "Agar hum monthly expenses saath mein track karein, to money kahan ja raha hai is confusion se bach sakte hain.",
    },
    support: {
      text: "This will also help us plan for school fees and repairs.",
      hiDeva: "इससे school fees और repairs के लिए plan करने में भी help मिलेगी।",
      hiLatn: "Isse school fees aur repairs ke liye plan karne mein bhi help milegi.",
    },
    keyPhrase: "If",
    keyOptions: ["If", "Unless", "Before"],
    keyExplanation: {
      hiDeva: "'If' condition बताता है: अगर हम track करें, तो confusion कम होगा।",
      hiLatn: "'If' condition batata hai: agar hum track karein, to confusion kam hoga.",
    },
    incorrect: "We track monthly expenses together we avoid confusion money going.",
    wrong: "If monthly expenses tracking together avoid where money going confusion.",
    speak: {
      text: "We can avoid confusion about where the money is going.",
      hiDeva: "Money कहाँ जा रहा है, इस confusion से हम बच सकते हैं।",
      hiLatn: "Money kahan ja raha hai, is confusion se hum bach sakte hain.",
    },
    tags: ["decision-discussion", "planning", "reason-connector", "summary"],
  },
  {
    id: "respond-to-unfair-comment",
    moduleId: "advanced-home-decisions",
    title: "Respond To An Unfair Comment",
    overview: "You will practice answering an unfair comment calmly without escalating.",
    skipOverview: ["Naming the feeling", "Correcting the assumption", "Requesting a fair discussion"],
    main: {
      text: "I felt hurt by that comment because it did not consider how much work I already do.",
      hiDeva: "उस comment से मुझे hurt feel हुआ क्योंकि उसमें मेरे already किए गए काम को consider नहीं किया गया।",
      hiLatn: "Us comment se mujhe hurt feel hua kyunki usmein mere already kiye gaye kaam ko consider nahi kiya gaya.",
    },
    support: {
      text: "Can we discuss this without blaming each other?",
      hiDeva: "क्या हम इस पर बिना blame किए बात कर सकते हैं?",
      hiLatn: "Kya hum is par bina blame kiye baat kar sakte hain?",
    },
    keyPhrase: "because",
    keyOptions: ["because", "before", "unless"],
    keyExplanation: {
      hiDeva: "'Because' feeling का reason clear करता है।",
      hiLatn: "'Because' feeling ka reason clear karta hai.",
    },
    incorrect: "I hurt by that comment because not consider my work.",
    wrong: "That comment hurt because work already much I do not consider.",
    speak: {
      text: "Can we discuss this without blaming each other?",
      hiDeva: "क्या हम इस पर बिना एक-दूसरे को blame किए बात कर सकते हैं?",
      hiLatn: "Kya hum is par bina ek-doosre ko blame kiye baat kar sakte hain?",
    },
    tags: ["polite-disagreement", "confidence", "family", "reason-connector"],
  },
  {
    id: "explain-recurring-symptom-pattern",
    moduleId: "healthcare-advocacy",
    title: "Explain A Recurring Symptom Pattern",
    overview: "You will practice explaining when a health problem keeps coming back.",
    skipOverview: ["Naming the pattern", "Saying when it happens", "Asking what to monitor"],
    main: {
      text: "The pain reduces after medicine, but it returns every evening when I start cooking.",
      hiDeva: "Medicine के बाद pain कम होता है, लेकिन हर evening cooking शुरू करने पर वापस आ जाता है।",
      hiLatn: "Medicine ke baad pain kam hota hai, lekin har evening cooking shuru karne par wapas aa jaata hai.",
    },
    support: {
      text: "Should I note the timing and intensity for a few days?",
      hiDeva: "क्या मुझे कुछ दिनों तक timing और intensity note करनी चाहिए?",
      hiLatn: "Kya mujhe kuch dinon tak timing aur intensity note karni chahiye?",
    },
    keyPhrase: "but",
    keyOptions: ["but", "so", "until"],
    keyExplanation: {
      hiDeva: "'But' improvement और returning problem के बीच contrast दिखाता है।",
      hiLatn: "'But' improvement aur returning problem ke beech contrast dikhata hai.",
    },
    incorrect: "Pain reduces medicine but returns every evening when cooking start.",
    wrong: "The pain reduce after medicine but every evening cooking returns.",
    speak: {
      text: "It returns every evening when I start cooking.",
      hiDeva: "यह हर evening cooking शुरू करने पर वापस आता है।",
      hiLatn: "Yeh har evening cooking shuru karne par wapas aata hai.",
    },
    tags: ["clinic-health", "time-prepositions", "contrast-connector", "follow-up-question"],
  },
  {
    id: "ask-for-second-opinion",
    moduleId: "healthcare-advocacy",
    title: "Ask For A Second Opinion",
    overview: "You will practice asking for another medical opinion politely.",
    skipOverview: ["Acknowledging current advice", "Asking for another view", "Staying respectful"],
    main: {
      text: "I respect your advice, but I would like to understand whether a second opinion is necessary.",
      hiDeva: "मैं आपकी advice respect करती हूँ, लेकिन समझना चाहती हूँ कि second opinion ज़रूरी है या नहीं।",
      hiLatn: "Main aapki advice respect karti hoon, lekin samajhna chahti hoon ki second opinion zaroori hai ya nahi.",
    },
    support: {
      text: "I want to make the decision carefully before starting long-term treatment.",
      hiDeva: "Long-term treatment शुरू करने से पहले मैं decision carefully लेना चाहती हूँ।",
      hiLatn: "Long-term treatment shuru karne se pehle main decision carefully lena chahti hoon.",
    },
    keyPhrase: "whether",
    keyOptions: ["whether", "weather", "where"],
    keyExplanation: {
      hiDeva: "'Whether' दो possibilities पूछने के लिए use होता है: ज़रूरी है या नहीं।",
      hiLatn: "'Whether' do possibilities poochne ke liye use hota hai: zaroori hai ya nahi.",
    },
    incorrect: "I respect advice but want understand second opinion necessary.",
    wrong: "I respect your advice but whether second opinion necessary understand like.",
    speak: {
      text: "I would like to understand whether a second opinion is necessary.",
      hiDeva: "मैं समझना चाहती हूँ कि second opinion ज़रूरी है या नहीं।",
      hiLatn: "Main samajhna chahti hoon ki second opinion zaroori hai ya nahi.",
    },
    tags: ["clinic-health", "clarification", "polite-request", "decision-discussion"],
  },
  {
    id: "discuss-caregiver-burnout",
    moduleId: "healthcare-advocacy",
    title: "Discuss Caregiver Burnout",
    overview: "You will practice explaining caregiver exhaustion and asking for help.",
    skipOverview: ["Naming the exhaustion", "Explaining the care load", "Requesting shared support"],
    main: {
      text: "I want to care for everyone properly, but I am becoming exhausted without regular support.",
      hiDeva: "मैं सबका care properly करना चाहती हूँ, लेकिन regular support के बिना exhausted हो रही हूँ।",
      hiLatn: "Main sabka care properly karna chahti hoon, lekin regular support ke bina exhausted ho rahi hoon.",
    },
    support: {
      text: "Can we make a weekly support plan instead of deciding everything at the last minute?",
      hiDeva: "क्या हम last minute decide करने के बजाय weekly support plan बना सकते हैं?",
      hiLatn: "Kya hum last minute decide karne ke bajay weekly support plan bana sakte hain?",
    },
    keyPhrase: "without",
    keyOptions: ["without", "within", "until"],
    keyExplanation: {
      hiDeva: "'Without regular support' बताता है कि support न होने से problem बढ़ रही है।",
      hiLatn: "'Without regular support' batata hai ki support na hone se problem badh rahi hai.",
    },
    incorrect: "I want care everyone properly but becoming exhausted regular support without.",
    wrong: "I becoming exhausted but care everyone properly support without regular.",
    speak: {
      text: "I am becoming exhausted without regular support.",
      hiDeva: "Regular support के बिना मैं exhausted हो रही हूँ।",
      hiLatn: "Regular support ke bina main exhausted ho rahi hoon.",
    },
    tags: ["clinic-health", "family", "confidence", "polite-request"],
  },
  {
    id: "clarify-test-report",
    moduleId: "healthcare-advocacy",
    title: "Clarify A Test Report",
    overview: "You will practice asking a doctor to explain report results in simple terms.",
    skipOverview: ["Saying what is unclear", "Requesting simple language", "Checking next steps"],
    main: {
      text: "Could you explain this report in simple words, especially the part that is marked high?",
      hiDeva: "क्या आप यह report simple words में explain कर सकते हैं, especially वह part जो high marked है?",
      hiLatn: "Kya aap yeh report simple words mein explain kar sakte hain, especially woh part jo high marked hai?",
    },
    support: {
      text: "I want to understand what I should do next.",
      hiDeva: "मैं समझना चाहती हूँ कि मुझे next क्या करना चाहिए।",
      hiLatn: "Main samajhna chahti hoon ki mujhe next kya karna chahiye.",
    },
    keyPhrase: "especially",
    keyOptions: ["especially", "slowly", "already"],
    keyExplanation: {
      hiDeva: "'Especially' important part पर focus करता है।",
      hiLatn: "'Especially' important part par focus karta hai.",
    },
    incorrect: "Explain this report simple words especially part marked high.",
    wrong: "Could you explain simple this report marked high especially part?",
    speak: {
      text: "Please explain this report in simple words.",
      hiDeva: "कृपया यह report simple words में explain कीजिए।",
      hiLatn: "Please yeh report simple words mein explain kijiye.",
    },
    tags: ["clinic-health", "clarification", "polite-request", "follow-up-question"],
  },
  {
    id: "describe-medicine-side-effect",
    moduleId: "healthcare-advocacy",
    title: "Describe A Medicine Side Effect",
    overview: "You will practice describing a side effect and asking whether to continue medicine.",
    skipOverview: ["Naming the side effect", "Saying when it started", "Asking for safe advice"],
    main: {
      text: "Since I started this medicine, I feel sleepy during the day and I cannot finish my work properly.",
      hiDeva: "जब से मैंने यह medicine शुरू की है, मुझे दिन में sleepy feel होता है और मैं काम properly finish नहीं कर पाती।",
      hiLatn: "Jab se maine yeh medicine shuru ki hai, mujhe din mein sleepy feel hota hai aur main kaam properly finish nahi kar paati.",
    },
    support: {
      text: "Should I continue the same dose or change the timing?",
      hiDeva: "क्या मुझे same dose continue करनी चाहिए या timing change करनी चाहिए?",
      hiLatn: "Kya mujhe same dose continue karni chahiye ya timing change karni chahiye?",
    },
    keyPhrase: "Since",
    keyOptions: ["Since", "Before", "Unless"],
    keyExplanation: {
      hiDeva: "'Since I started...' बताता है कि symptom कब से शुरू हुआ।",
      hiLatn: "'Since I started...' batata hai ki symptom kab se shuru hua.",
    },
    incorrect: "Since started medicine I sleepy day and cannot finish work properly.",
    wrong: "I feel sleepy since medicine during day cannot work finish properly.",
    speak: {
      text: "I feel sleepy during the day.",
      hiDeva: "मुझे दिन में sleepy feel होता है।",
      hiLatn: "Mujhe din mein sleepy feel hota hai.",
    },
    tags: ["clinic-health", "present-perfect", "advice-question", "problem-reporting"],
  },
  {
    id: "describe-home-business-idea",
    moduleId: "work-skills-income",
    title: "Describe A Home Business Idea",
    overview: "You will practice explaining a small earning idea with confidence.",
    skipOverview: ["Naming the idea", "Explaining the customer need", "Saying how you will start"],
    main: {
      text: "I am planning to start a small snack business from home because many parents need fresh evening options.",
      hiDeva: "मैं home से small snack business शुरू करने की planning कर रही हूँ क्योंकि कई parents को fresh evening options चाहिए।",
      hiLatn: "Main home se small snack business shuru karne ki planning kar rahi hoon kyunki kai parents ko fresh evening options chahiye.",
    },
    support: {
      text: "I will begin with a weekly menu and take limited orders first.",
      hiDeva: "मैं weekly menu से शुरू करूँगी और पहले limited orders लूँगी।",
      hiLatn: "Main weekly menu se shuru karungi aur pehle limited orders lungi.",
    },
    keyPhrase: "because",
    keyOptions: ["because", "although", "unless"],
    keyExplanation: {
      hiDeva: "'Because' business idea का reason बताता है।",
      hiLatn: "'Because' business idea ka reason batata hai.",
    },
    incorrect: "I planning start snack business home because parents need evening fresh options.",
    wrong: "Planning snack business because options fresh parents from home need.",
    speak: {
      text: "I will begin with a weekly menu.",
      hiDeva: "मैं weekly menu से शुरू करूँगी।",
      hiLatn: "Main weekly menu se shuru karungi.",
    },
    tags: ["future-plan", "confidence", "reason-connector", "planning"],
  },
  {
    id: "explain-work-gap-confidently",
    moduleId: "work-skills-income",
    title: "Explain A Work Gap Confidently",
    overview: "You will practice explaining a career gap without apologizing too much.",
    skipOverview: ["Naming the gap", "Explaining responsibility", "Showing readiness now"],
    main: {
      text: "I took a break from paid work to manage family responsibilities, and now I am ready to restart.",
      hiDeva: "मैंने family responsibilities manage करने के लिए paid work से break लिया था, और अब restart करने के लिए ready हूँ।",
      hiLatn: "Maine family responsibilities manage karne ke liye paid work se break liya tha, aur ab restart karne ke liye ready hoon.",
    },
    support: {
      text: "During that time, I improved my planning, communication, and problem-solving skills.",
      hiDeva: "उस दौरान मैंने planning, communication, और problem-solving skills improve कीं।",
      hiLatn: "Us dauran maine planning, communication, aur problem-solving skills improve ki.",
    },
    keyPhrase: "to manage",
    keyOptions: ["to manage", "managing", "managed"],
    keyExplanation: {
      hiDeva: "'To manage' reason बताता है कि break क्यों लिया गया।",
      hiLatn: "'To manage' reason batata hai ki break kyun liya gaya.",
    },
    incorrect: "I took break paid work manage family responsibilities now ready restart.",
    wrong: "I took break to manage family and now ready restarting paid work.",
    speak: {
      text: "Now I am ready to restart.",
      hiDeva: "अब मैं restart करने के लिए ready हूँ।",
      hiLatn: "Ab main restart karne ke liye ready hoon.",
    },
    tags: ["confidence", "formal-follow-up", "future-plan", "summary"],
  },
  {
    id: "discuss-flexible-work-need",
    moduleId: "work-skills-income",
    title: "Discuss Flexible Work Needs",
    overview: "You will practice asking about flexible work in a professional way.",
    skipOverview: ["Stating availability", "Explaining the reason briefly", "Asking about options"],
    main: {
      text: "I can work reliably if the timing is flexible around school pickup and family care.",
      hiDeva: "अगर timing school pickup और family care के आसपास flexible हो, तो मैं reliably काम कर सकती हूँ।",
      hiLatn: "Agar timing school pickup aur family care ke aas-paas flexible ho, to main reliably kaam kar sakti hoon.",
    },
    support: {
      text: "Could you tell me whether part-time hours are available?",
      hiDeva: "क्या आप बता सकते हैं कि part-time hours available हैं या नहीं?",
      hiLatn: "Kya aap bata sakte hain ki part-time hours available hain ya nahi?",
    },
    keyPhrase: "if",
    keyOptions: ["if", "until", "although"],
    keyExplanation: {
      hiDeva: "'If' condition बताता है: flexible timing हो तो काम possible है।",
      hiLatn: "'If' condition batata hai: flexible timing ho to kaam possible hai.",
    },
    incorrect: "I can work reliable if timing flexible around school pickup family care.",
    wrong: "Timing flexible if I work reliably can around school pickup.",
    speak: {
      text: "Could you tell me whether part-time hours are available?",
      hiDeva: "क्या आप बता सकते हैं कि part-time hours available हैं या नहीं?",
      hiLatn: "Kya aap bata sakte hain ki part-time hours available hain ya nahi?",
    },
    tags: ["availability", "polite-request", "question-formation", "confidence"],
  },
  {
    id: "handle-customer-complaint",
    moduleId: "work-skills-income",
    title: "Handle A Customer Complaint",
    overview: "You will practice responding calmly when a customer is unhappy.",
    skipOverview: ["Acknowledging the issue", "Apologizing without panic", "Offering a practical fix"],
    main: {
      text: "I am sorry the order was delayed; I can replace it today or adjust the amount in your next order.",
      hiDeva: "Order delay हुआ, इसके लिए sorry; मैं इसे आज replace कर सकती हूँ या next order में amount adjust कर सकती हूँ।",
      hiLatn: "Order delay hua, iske liye sorry; main ise aaj replace kar sakti hoon ya next order mein amount adjust kar sakti hoon.",
    },
    support: {
      text: "Please tell me which option works better for you.",
      hiDeva: "कृपया बताइए कौन सा option आपके लिए बेहतर रहेगा।",
      hiLatn: "Please batayiye kaunsa option aapke liye better rahega.",
    },
    keyPhrase: "or",
    keyOptions: ["or", "but", "because"],
    keyExplanation: {
      hiDeva: "'Or' customer को दो options देता है।",
      hiLatn: "'Or' customer ko do options deta hai.",
    },
    incorrect: "Sorry order delayed I replace today or adjust amount next order.",
    wrong: "I sorry delayed order replace today adjust amount next order or.",
    speak: {
      text: "Please tell me which option works better for you.",
      hiDeva: "कृपया बताइए कौन सा option आपके लिए बेहतर रहेगा।",
      hiLatn: "Please batayiye kaunsa option aapke liye better rahega.",
    },
    tags: ["problem-solving", "polite-request", "service-request", "confidence"],
  },
  {
    id: "present-skill-achievement",
    moduleId: "work-skills-income",
    title: "Present A Skill Achievement",
    overview: "You will practice talking about a skill you built through real life.",
    skipOverview: ["Naming the skill", "Giving proof", "Connecting it to future work"],
    main: {
      text: "Managing the household budget has helped me become more organized and careful with details.",
      hiDeva: "Household budget manage करने से मैं ज़्यादा organized और details के साथ careful बनी हूँ।",
      hiLatn: "Household budget manage karne se main zyada organized aur details ke saath careful bani hoon.",
    },
    support: {
      text: "I can use the same discipline in customer records and daily planning.",
      hiDeva: "मैं वही discipline customer records और daily planning में use कर सकती हूँ।",
      hiLatn: "Main wahi discipline customer records aur daily planning mein use kar sakti hoon.",
    },
    keyPhrase: "has helped",
    keyOptions: ["has helped", "have help", "helping"],
    keyExplanation: {
      hiDeva: "'Has helped me become...' past experience का present result बताता है।",
      hiLatn: "'Has helped me become...' past experience ka present result batata hai.",
    },
    incorrect: "Managing household budget helped me become organized careful details.",
    wrong: "Household budget has help me organized and careful details.",
    speak: {
      text: "It has helped me become more organized.",
      hiDeva: "इससे मैं ज़्यादा organized बनी हूँ।",
      hiLatn: "Isse main zyada organized bani hoon.",
    },
    tags: ["present-perfect", "confidence", "summary", "daily-routine"],
  },
  {
    id: "discuss-learning-difficulty",
    moduleId: "education-advocacy",
    title: "Discuss A Learning Difficulty",
    overview: "You will practice describing a child's learning difficulty without shame.",
    skipOverview: ["Naming the difficulty", "Giving an example", "Requesting guidance"],
    main: {
      text: "He understands the lesson when it is explained aloud, but he struggles to write the answer independently.",
      hiDeva: "जब lesson aloud explain होता है तो वह समझता है, लेकिन answer independently लिखने में struggle करता है।",
      hiLatn: "Jab lesson aloud explain hota hai to woh samajhta hai, lekin answer independently likhne mein struggle karta hai.",
    },
    support: {
      text: "Could you suggest one practice method we can follow at home?",
      hiDeva: "क्या आप एक practice method suggest कर सकते हैं जिसे हम घर पर follow करें?",
      hiLatn: "Kya aap ek practice method suggest kar sakte hain jise hum ghar par follow karein?",
    },
    keyPhrase: "but",
    keyOptions: ["but", "because", "after"],
    keyExplanation: {
      hiDeva: "'But' strength और difficulty दोनों को balance करता है।",
      hiLatn: "'But' strength aur difficulty dono ko balance karta hai.",
    },
    incorrect: "He understands lesson explained aloud but struggles write answer independently.",
    wrong: "He understand aloud lesson but write answer struggles independently.",
    speak: {
      text: "He struggles to write the answer independently.",
      hiDeva: "उसे answer independently लिखने में struggle होता है।",
      hiLatn: "Use answer independently likhne mein struggle hota hai.",
    },
    tags: ["school-family", "contrast-connector", "problem-reporting", "polite-request"],
  },
  {
    id: "request-parent-teacher-action-plan",
    moduleId: "education-advocacy",
    title: "Request A Parent-Teacher Action Plan",
    overview: "You will practice asking for clear follow-up after a school meeting.",
    skipOverview: ["Summarizing the concern", "Requesting action steps", "Checking timeline"],
    main: {
      text: "Can we make a simple action plan so that I know exactly what to practice at home?",
      hiDeva: "क्या हम simple action plan बना सकते हैं ताकि मुझे exactly पता हो कि घर पर क्या practice करना है?",
      hiLatn: "Kya hum simple action plan bana sakte hain taaki mujhe exactly pata ho ki ghar par kya practice karna hai?",
    },
    support: {
      text: "I can review it every Sunday and share progress with you.",
      hiDeva: "मैं इसे हर Sunday review कर सकती हूँ और progress आपके साथ share कर सकती हूँ।",
      hiLatn: "Main ise har Sunday review kar sakti hoon aur progress aapke saath share kar sakti hoon.",
    },
    keyPhrase: "so that",
    keyOptions: ["so that", "because of", "unless"],
    keyExplanation: {
      hiDeva: "'So that' purpose बताता है: action plan क्यों चाहिए।",
      hiLatn: "'So that' purpose batata hai: action plan kyun chahiye.",
    },
    incorrect: "Can we make simple action plan I know exactly practice home?",
    wrong: "Can make action plan so that exactly home practice know I?",
    speak: {
      text: "Can we make a simple action plan?",
      hiDeva: "क्या हम simple action plan बना सकते हैं?",
      hiLatn: "Kya hum simple action plan bana sakte hain?",
    },
    tags: ["school-family", "purpose-connector", "planning", "follow-up-question"],
  },
  {
    id: "explain-child-emotional-change",
    moduleId: "education-advocacy",
    title: "Explain A Child's Emotional Change",
    overview: "You will practice explaining emotional changes with examples.",
    skipOverview: ["Naming the change", "Giving a recent example", "Asking for observation"],
    main: {
      text: "Recently she has become quiet after school, and I am wondering whether something is bothering her.",
      hiDeva: "Recently वह school के बाद quiet हो गई है, और मैं सोच रही हूँ कि क्या उसे कुछ bother कर रहा है।",
      hiLatn: "Recently woh school ke baad quiet ho gayi hai, aur main soch rahi hoon ki kya use kuch bother kar raha hai.",
    },
    support: {
      text: "Have you noticed any change in class participation?",
      hiDeva: "क्या आपने class participation में कोई change notice किया है?",
      hiLatn: "Kya aapne class participation mein koi change notice kiya hai?",
    },
    keyPhrase: "whether",
    keyOptions: ["whether", "weather", "where"],
    keyExplanation: {
      hiDeva: "'Whether something is bothering her' doubt को gentle way में पूछता है।",
      hiLatn: "'Whether something is bothering her' doubt ko gentle way mein poochta hai.",
    },
    incorrect: "Recently she quiet after school and I wondering something bothering her.",
    wrong: "She has become quiet after school whether wondering bothering her.",
    speak: {
      text: "Have you noticed any change in class participation?",
      hiDeva: "क्या आपने class participation में कोई change notice किया है?",
      hiLatn: "Kya aapne class participation mein koi change notice kiya hai?",
    },
    tags: ["school-family", "present-perfect", "follow-up-question", "problem-reporting"],
  },
  {
    id: "ask-about-exam-preparation",
    moduleId: "education-advocacy",
    title: "Ask About Exam Preparation",
    overview: "You will practice asking how to prepare without creating pressure.",
    skipOverview: ["Asking about important topics", "Checking daily practice", "Keeping stress low"],
    main: {
      text: "Which topics should we revise first so that she feels prepared without becoming too stressed?",
      hiDeva: "हमें कौन से topics पहले revise करने चाहिए ताकि वह prepared feel करे और बहुत stressed न हो?",
      hiLatn: "Humein kaun se topics pehle revise karne chahiye taaki woh prepared feel kare aur bahut stressed na ho?",
    },
    support: {
      text: "A short daily plan will be easier for us to follow.",
      hiDeva: "Short daily plan हमारे लिए follow करना आसान रहेगा।",
      hiLatn: "Short daily plan hamare liye follow karna easy rahega.",
    },
    keyPhrase: "without",
    keyOptions: ["without", "within", "because"],
    keyExplanation: {
      hiDeva: "'Without becoming too stressed' बताता है कि preparation balanced होनी चाहिए।",
      hiLatn: "'Without becoming too stressed' batata hai ki preparation balanced honi chahiye.",
    },
    incorrect: "Which topics revise first so she prepared without too stressed becoming?",
    wrong: "Which topics should first revise she prepared stressed without?",
    speak: {
      text: "A short daily plan will be easier to follow.",
      hiDeva: "Short daily plan follow करना आसान रहेगा।",
      hiLatn: "Short daily plan follow karna easy rahega.",
    },
    tags: ["school-family", "modal-should", "planning", "question-formation"],
  },
  {
    id: "discuss-digital-safety-with-school",
    moduleId: "education-advocacy",
    title: "Discuss Digital Safety With School",
    overview: "You will practice asking about online safety and school support.",
    skipOverview: ["Naming the digital concern", "Asking about school rules", "Requesting practical guidance"],
    main: {
      text: "I want to understand how the school teaches children to stay safe while using online learning apps.",
      hiDeva: "मैं समझना चाहती हूँ कि school बच्चों को online learning apps use करते समय safe रहना कैसे सिखाता है।",
      hiLatn: "Main samajhna chahti hoon ki school bachchon ko online learning apps use karte samay safe rehna kaise sikhata hai.",
    },
    support: {
      text: "Could you share the basic rules that parents should repeat at home?",
      hiDeva: "क्या आप basic rules share कर सकते हैं जो parents को घर पर repeat करने चाहिए?",
      hiLatn: "Kya aap basic rules share kar sakte hain jo parents ko ghar par repeat karne chahiye?",
    },
    keyPhrase: "while",
    keyOptions: ["while", "because", "unless"],
    keyExplanation: {
      hiDeva: "'While using...' बताता है कि safety किस activity के दौरान चाहिए।",
      hiLatn: "'While using...' batata hai ki safety kis activity ke dauran chahiye.",
    },
    incorrect: "I want understand how school teach children safe online learning apps using.",
    wrong: "School teaches children safe while online apps how I understand want.",
    speak: {
      text: "Could you share the basic rules?",
      hiDeva: "क्या आप basic rules share कर सकते हैं?",
      hiLatn: "Kya aap basic rules share kar sakte hain?",
    },
    tags: ["school-family", "clarification", "polite-request", "problem-solving"],
  },
  {
    id: "file-formal-service-complaint",
    moduleId: "civic-and-services",
    title: "File A Formal Service Complaint",
    overview: "You will practice describing a service complaint with facts and dates.",
    skipOverview: ["Naming the service issue", "Giving a date", "Requesting a complaint number"],
    main: {
      text: "I am filing this complaint because the water supply has been irregular for three weeks.",
      hiDeva: "मैं यह complaint file कर रही हूँ क्योंकि water supply तीन weeks से irregular है।",
      hiLatn: "Main yeh complaint file kar rahi hoon kyunki water supply teen weeks se irregular hai.",
    },
    support: {
      text: "Please give me a complaint number so I can follow up.",
      hiDeva: "कृपया मुझे complaint number दीजिए ताकि मैं follow up कर सकूँ।",
      hiLatn: "Please mujhe complaint number dijiye taaki main follow up kar sakun.",
    },
    keyPhrase: "because",
    keyOptions: ["because", "although", "before"],
    keyExplanation: {
      hiDeva: "'Because' complaint का reason formally बताता है।",
      hiLatn: "'Because' complaint ka reason formally batata hai.",
    },
    incorrect: "I filing complaint because water supply irregular three weeks.",
    wrong: "Complaint filing because three weeks water supply irregular has been.",
    speak: {
      text: "Please give me a complaint number.",
      hiDeva: "कृपया मुझे complaint number दीजिए।",
      hiLatn: "Please mujhe complaint number dijiye.",
    },
    tags: ["formal-follow-up", "service-request", "present-perfect", "problem-reporting"],
  },
  {
    id: "follow-up-government-office",
    moduleId: "civic-and-services",
    title: "Follow Up With A Government Office",
    overview: "You will practice asking for status without sounding impatient.",
    skipOverview: ["Giving application details", "Asking for status", "Requesting next steps"],
    main: {
      text: "I submitted the form last month, and I would like to know whether any document is still pending.",
      hiDeva: "मैंने form last month submit किया था, और जानना चाहती हूँ कि कोई document अभी भी pending है या नहीं।",
      hiLatn: "Maine form last month submit kiya tha, aur jaanna chahti hoon ki koi document abhi bhi pending hai ya nahi.",
    },
    support: {
      text: "Please tell me the next step if something is missing.",
      hiDeva: "अगर कुछ missing है, तो कृपया next step बताइए।",
      hiLatn: "Agar kuch missing hai, to please next step batayiye.",
    },
    keyPhrase: "whether",
    keyOptions: ["whether", "weather", "where"],
    keyExplanation: {
      hiDeva: "'Whether any document is pending' status पूछने का formal तरीका है।",
      hiLatn: "'Whether any document is pending' status poochne ka formal tareeka hai.",
    },
    incorrect: "I submitted form last month want know document pending still.",
    wrong: "I would like know whether document still pending submitted form.",
    speak: {
      text: "I would like to know whether any document is still pending.",
      hiDeva: "मैं जानना चाहती हूँ कि कोई document अभी भी pending है या नहीं।",
      hiLatn: "Main jaanna chahti hoon ki koi document abhi bhi pending hai ya nahi.",
    },
    tags: ["formal-follow-up", "clarification", "present-perfect", "polite-request"],
  },
  {
    id: "explain-neighborhood-safety-pattern",
    moduleId: "civic-and-services",
    title: "Explain A Neighborhood Safety Pattern",
    overview: "You will practice explaining repeated safety concerns with examples.",
    skipOverview: ["Naming the pattern", "Giving frequency", "Requesting prevention"],
    main: {
      text: "There have been repeated power cuts near the gate, especially after heavy rain.",
      hiDeva: "Gate के पास repeated power cuts हुए हैं, especially heavy rain के बाद।",
      hiLatn: "Gate ke paas repeated power cuts hue hain, especially heavy rain ke baad.",
    },
    support: {
      text: "This area becomes unsafe because the street lights stop working.",
      hiDeva: "यह area unsafe हो जाता है क्योंकि street lights काम करना बंद कर देती हैं।",
      hiLatn: "Yeh area unsafe ho jaata hai kyunki street lights kaam karna band kar deti hain.",
    },
    keyPhrase: "especially",
    keyOptions: ["especially", "already", "slowly"],
    keyExplanation: {
      hiDeva: "'Especially after heavy rain' pattern को specific बनाता है।",
      hiLatn: "'Especially after heavy rain' pattern ko specific banata hai.",
    },
    incorrect: "There have repeated power cuts gate especially after heavy rain.",
    wrong: "Repeated power cuts there have been near gate heavy rain especially.",
    speak: {
      text: "This area becomes unsafe after heavy rain.",
      hiDeva: "Heavy rain के बाद यह area unsafe हो जाता है।",
      hiLatn: "Heavy rain ke baad yeh area unsafe ho jaata hai.",
    },
    tags: ["problem-reporting", "present-perfect", "reason-connector", "service-request"],
  },
  {
    id: "request-clear-timeline",
    moduleId: "civic-and-services",
    title: "Request A Clear Timeline",
    overview: "You will practice asking for dates and next updates clearly.",
    skipOverview: ["Asking for a timeline", "Requesting written confirmation", "Clarifying responsibility"],
    main: {
      text: "Could you please give me a clear timeline so I know when the repair team will visit?",
      hiDeva: "क्या आप please clear timeline दे सकते हैं ताकि मुझे पता हो repair team कब visit करेगी?",
      hiLatn: "Kya aap please clear timeline de sakte hain taaki mujhe pata ho repair team kab visit karegi?",
    },
    support: {
      text: "A written update will help me coordinate with the family.",
      hiDeva: "Written update से मुझे family के साथ coordinate करने में help मिलेगी।",
      hiLatn: "Written update se mujhe family ke saath coordinate karne mein help milegi.",
    },
    keyPhrase: "so",
    keyOptions: ["so", "although", "unless"],
    keyExplanation: {
      hiDeva: "'So I know...' timeline माँगने का purpose बताता है।",
      hiLatn: "'So I know...' timeline maangne ka purpose batata hai.",
    },
    incorrect: "Please give clear timeline I know when repair team visit.",
    wrong: "Could give me clear timeline repair team when visit know?",
    speak: {
      text: "Could you please give me a clear timeline?",
      hiDeva: "क्या आप please clear timeline दे सकते हैं?",
      hiLatn: "Kya aap please clear timeline de sakte hain?",
    },
    tags: ["formal-follow-up", "polite-request", "time-prepositions", "clarification"],
  },
  {
    id: "escalate-unresolved-issue",
    moduleId: "civic-and-services",
    title: "Escalate An Unresolved Issue",
    overview: "You will practice escalating politely when earlier follow-ups have not worked.",
    skipOverview: ["Mentioning previous follow-ups", "Staying factual", "Requesting escalation"],
    main: {
      text: "I have followed up twice, but the issue is still unresolved, so please escalate it to the supervisor.",
      hiDeva: "मैं दो बार follow up कर चुकी हूँ, लेकिन issue अभी भी unresolved है, इसलिए please इसे supervisor तक escalate कीजिए।",
      hiLatn: "Main do baar follow up kar chuki hoon, lekin issue abhi bhi unresolved hai, isliye please ise supervisor tak escalate kijiye.",
    },
    support: {
      text: "I would appreciate an update by tomorrow evening.",
      hiDeva: "मैं tomorrow evening तक update appreciate करूँगी।",
      hiLatn: "Main tomorrow evening tak update appreciate karungi.",
    },
    keyPhrase: "so",
    keyOptions: ["so", "although", "before"],
    keyExplanation: {
      hiDeva: "'So' previous problem के बाद next action connect करता है।",
      hiLatn: "'So' previous problem ke baad next action connect karta hai.",
    },
    incorrect: "I followed up twice but issue still unresolved so escalate supervisor.",
    wrong: "Issue unresolved I followed twice supervisor please escalate so.",
    speak: {
      text: "Please escalate it to the supervisor.",
      hiDeva: "कृपया इसे supervisor तक escalate कीजिए।",
      hiLatn: "Please ise supervisor tak escalate kijiye.",
    },
    tags: ["formal-follow-up", "present-perfect", "service-request", "problem-solving"],
  },
  {
    id: "compare-loan-options",
    moduleId: "financial-confidence",
    title: "Compare Loan Options",
    overview: "You will practice comparing money options carefully.",
    skipOverview: ["Asking about total cost", "Comparing monthly payment", "Checking risk"],
    main: {
      text: "Before I decide, I need to compare the total cost, not only the monthly payment.",
      hiDeva: "Decision लेने से पहले मुझे total cost compare करनी है, सिर्फ monthly payment नहीं।",
      hiLatn: "Decision lene se pehle mujhe total cost compare karni hai, sirf monthly payment nahi.",
    },
    support: {
      text: "Please show me the interest and processing charges together.",
      hiDeva: "कृपया interest और processing charges साथ में दिखाइए।",
      hiLatn: "Please interest aur processing charges saath mein dikhaiye.",
    },
    keyPhrase: "Before",
    keyOptions: ["Before", "After", "Because"],
    keyExplanation: {
      hiDeva: "'Before I decide' बताता है कि decision से पहले information चाहिए।",
      hiLatn: "'Before I decide' batata hai ki decision se pehle information chahiye.",
    },
    incorrect: "Before decide I need compare total cost not only monthly payment.",
    wrong: "I need compare monthly payment before total cost not only decide.",
    speak: {
      text: "I need to compare the total cost.",
      hiDeva: "मुझे total cost compare करनी है।",
      hiLatn: "Mujhe total cost compare karni hai.",
    },
    tags: ["decision-discussion", "clarification", "polite-request", "preference"],
  },
  {
    id: "ask-about-hidden-charges",
    moduleId: "financial-confidence",
    title: "Ask About Hidden Charges",
    overview: "You will practice asking about extra charges without hesitation.",
    skipOverview: ["Naming possible charges", "Asking for written details", "Confirming total amount"],
    main: {
      text: "Could you confirm whether there are any charges apart from the amount shown here?",
      hiDeva: "क्या आप confirm कर सकते हैं कि यहाँ दिखे amount के अलावा कोई charges हैं या नहीं?",
      hiLatn: "Kya aap confirm kar sakte hain ki yahan dikhe amount ke alawa koi charges hain ya nahi?",
    },
    support: {
      text: "I would like the full amount in writing before I agree.",
      hiDeva: "Agree करने से पहले मैं full amount writing में चाहती हूँ।",
      hiLatn: "Agree karne se pehle main full amount writing mein chahti hoon.",
    },
    keyPhrase: "apart from",
    keyOptions: ["apart from", "instead of", "because of"],
    keyExplanation: {
      hiDeva: "'Apart from' का मतलब है shown amount के अलावा।",
      hiLatn: "'Apart from' ka matlab hai shown amount ke alawa.",
    },
    incorrect: "Confirm any charges apart from amount shown here?",
    wrong: "Could confirm charges whether amount apart shown here any?",
    speak: {
      text: "I would like the full amount in writing.",
      hiDeva: "मैं full amount writing में चाहती हूँ।",
      hiLatn: "Main full amount writing mein chahti hoon.",
    },
    tags: ["clarification", "formal-follow-up", "polite-request", "question-formation"],
  },
  {
    id: "explain-savings-goal",
    moduleId: "financial-confidence",
    title: "Explain A Savings Goal",
    overview: "You will practice explaining why you are saving and what tradeoff you are making.",
    skipOverview: ["Naming the goal", "Explaining the timeline", "Saying what you will reduce"],
    main: {
      text: "We are reducing small extra expenses this year so that we can save for our daughter's course.",
      hiDeva: "हम इस year small extra expenses reduce कर रहे हैं ताकि daughter के course के लिए save कर सकें।",
      hiLatn: "Hum is year small extra expenses reduce kar rahe hain taaki daughter ke course ke liye save kar saken.",
    },
    support: {
      text: "This goal is more important than buying new furniture right now.",
      hiDeva: "यह goal अभी new furniture खरीदने से ज़्यादा important है।",
      hiLatn: "Yeh goal abhi new furniture khareedne se zyada important hai.",
    },
    keyPhrase: "so that",
    keyOptions: ["so that", "because of", "until"],
    keyExplanation: {
      hiDeva: "'So that' saving का purpose बताता है।",
      hiLatn: "'So that' saving ka purpose batata hai.",
    },
    incorrect: "We reducing small expenses this year save daughter course.",
    wrong: "We reduce expenses so daughter course can save that.",
    speak: {
      text: "We are saving for our daughter's course.",
      hiDeva: "हम daughter के course के लिए save कर रहे हैं।",
      hiLatn: "Hum daughter ke course ke liye save kar rahe hain.",
    },
    tags: ["planning", "purpose-connector", "future-plan", "decision-discussion"],
  },
  {
    id: "discuss-insurance-claim",
    moduleId: "financial-confidence",
    title: "Discuss An Insurance Claim",
    overview: "You will practice explaining documents and asking about claim status.",
    skipOverview: ["Listing submitted documents", "Asking what is missing", "Requesting status"],
    main: {
      text: "I have submitted the bills and discharge summary, but the claim status has not changed.",
      hiDeva: "मैंने bills और discharge summary submit कर दी है, लेकिन claim status change नहीं हुआ।",
      hiLatn: "Maine bills aur discharge summary submit kar di hai, lekin claim status change nahi hua.",
    },
    support: {
      text: "Please tell me if any document is missing from my side.",
      hiDeva: "कृपया बताइए कि मेरी तरफ से कोई document missing है या नहीं।",
      hiLatn: "Please batayiye ki meri taraf se koi document missing hai ya nahi.",
    },
    keyPhrase: "but",
    keyOptions: ["but", "because", "after"],
    keyExplanation: {
      hiDeva: "'But' submitted documents और unchanged status के बीच contrast दिखाता है।",
      hiLatn: "'But' submitted documents aur unchanged status ke beech contrast dikhata hai.",
    },
    incorrect: "I submitted bills discharge summary but claim status not changed.",
    wrong: "Claim status not changed but bills submitted discharge summary have.",
    speak: {
      text: "The claim status has not changed.",
      hiDeva: "Claim status change नहीं हुआ है।",
      hiLatn: "Claim status change nahi hua hai.",
    },
    tags: ["present-perfect", "formal-follow-up", "clarification", "problem-reporting"],
  },
  {
    id: "refuse-unnecessary-purchase",
    moduleId: "financial-confidence",
    title: "Refuse An Unnecessary Purchase",
    overview: "You will practice refusing a sales push without sounding unsure.",
    skipOverview: ["Thanking the person", "Giving your decision", "Avoiding over-explanation"],
    main: {
      text: "Thank you for explaining the offer, but I do not want to make this purchase today.",
      hiDeva: "Offer explain करने के लिए thank you, लेकिन मैं आज यह purchase नहीं करना चाहती।",
      hiLatn: "Offer explain karne ke liye thank you, lekin main aaj yeh purchase nahi karna chahti.",
    },
    support: {
      text: "If I need it later, I will contact you.",
      hiDeva: "अगर मुझे बाद में इसकी ज़रूरत होगी, तो मैं आपसे contact करूँगी।",
      hiLatn: "Agar mujhe baad mein iski zaroorat hogi, to main aapse contact karungi.",
    },
    keyPhrase: "but",
    keyOptions: ["but", "because", "after"],
    keyExplanation: {
      hiDeva: "'But' polite thanks के बाद firm refusal देता है।",
      hiLatn: "'But' polite thanks ke baad firm refusal deta hai.",
    },
    incorrect: "Thank you explaining offer but I not want purchase today.",
    wrong: "I do not want make purchase today thank offer explaining but.",
    speak: {
      text: "I do not want to make this purchase today.",
      hiDeva: "मैं आज यह purchase नहीं करना चाहती।",
      hiLatn: "Main aaj yeh purchase nahi karna chahti.",
    },
    tags: ["negative-sentence", "polite-disagreement", "confidence", "decision-discussion"],
  },
  {
    id: "respond-to-pressure-politely",
    moduleId: "conflict-and-boundaries",
    title: "Respond To Pressure Politely",
    overview: "You will practice slowing down a decision when someone pressures you.",
    skipOverview: ["Acknowledging the request", "Asking for time", "Keeping the tone firm"],
    main: {
      text: "I understand this is important to you, but I need time to think before I answer.",
      hiDeva: "मैं समझती हूँ कि यह आपके लिए important है, लेकिन answer देने से पहले मुझे सोचने का time चाहिए।",
      hiLatn: "Main samajhti hoon ki yeh aapke liye important hai, lekin answer dene se pehle mujhe sochne ka time chahiye.",
    },
    support: {
      text: "I will give you a clear reply by tomorrow evening.",
      hiDeva: "मैं tomorrow evening तक clear reply दे दूँगी।",
      hiLatn: "Main tomorrow evening tak clear reply de dungi.",
    },
    keyPhrase: "before",
    keyOptions: ["before", "because", "unless"],
    keyExplanation: {
      hiDeva: "'Before I answer' बताता है कि answer से पहले सोचने का time चाहिए।",
      hiLatn: "'Before I answer' batata hai ki answer se pehle sochne ka time chahiye.",
    },
    incorrect: "I understand important to you but need time think before answer.",
    wrong: "Before answer I understand important but time think need.",
    speak: {
      text: "I need time to think before I answer.",
      hiDeva: "Answer देने से पहले मुझे सोचने का time चाहिए।",
      hiLatn: "Answer dene se pehle mujhe sochne ka time chahiye.",
    },
    tags: ["polite-disagreement", "confidence", "future-plan", "time-prepositions"],
  },
  {
    id: "disagree-with-family-respectfully",
    moduleId: "conflict-and-boundaries",
    title: "Disagree With Family Respectfully",
    overview: "You will practice disagreeing without insulting the other person.",
    skipOverview: ["Respecting the other view", "Stating your view", "Explaining why"],
    main: {
      text: "I respect your point, but I see this situation differently because the timing is difficult for us.",
      hiDeva: "मैं आपकी बात respect करती हूँ, लेकिन इस situation को differently देखती हूँ क्योंकि timing हमारे लिए difficult है।",
      hiLatn: "Main aapki baat respect karti hoon, lekin is situation ko differently dekhti hoon kyunki timing hamare liye difficult hai.",
    },
    support: {
      text: "Can we look for another option that works for both sides?",
      hiDeva: "क्या हम ऐसा दूसरा option ढूँढ सकते हैं जो दोनों sides के लिए work करे?",
      hiLatn: "Kya hum aisa doosra option dhoondh sakte hain jo dono sides ke liye work kare?",
    },
    keyPhrase: "because",
    keyOptions: ["because", "before", "although"],
    keyExplanation: {
      hiDeva: "'Because' disagreement का reason calmly बताता है।",
      hiLatn: "'Because' disagreement ka reason calmly batata hai.",
    },
    incorrect: "I respect your point but see situation differently because timing difficult us.",
    wrong: "I respect point differently because timing difficult situation us.",
    speak: {
      text: "I see this situation differently.",
      hiDeva: "मैं इस situation को differently देखती हूँ।",
      hiLatn: "Main is situation ko differently dekhti hoon.",
    },
    tags: ["polite-disagreement", "reason-connector", "family", "preference"],
  },
  {
    id: "set-time-boundary",
    moduleId: "conflict-and-boundaries",
    title: "Set A Time Boundary",
    overview: "You will practice saying when you are available and when you are not.",
    skipOverview: ["Naming your available time", "Saying what is not possible", "Offering an alternative"],
    main: {
      text: "I can discuss this after dinner, but I cannot handle a serious conversation while I am cooking.",
      hiDeva: "मैं dinner के बाद इस पर बात कर सकती हूँ, लेकिन cooking करते समय serious conversation handle नहीं कर सकती।",
      hiLatn: "Main dinner ke baad is par baat kar sakti hoon, lekin cooking karte samay serious conversation handle nahi kar sakti.",
    },
    support: {
      text: "If we talk later, I will be able to listen properly.",
      hiDeva: "अगर हम बाद में बात करें, तो मैं properly listen कर पाऊँगी।",
      hiLatn: "Agar hum baad mein baat karein, to main properly listen kar paungi.",
    },
    keyPhrase: "while",
    keyOptions: ["while", "because", "after"],
    keyExplanation: {
      hiDeva: "'While I am cooking' बताता है कि उसी समय serious बात possible नहीं है।",
      hiLatn: "'While I am cooking' batata hai ki usi samay serious baat possible nahi hai.",
    },
    incorrect: "I discuss after dinner but cannot serious conversation while cooking.",
    wrong: "I can discuss after dinner but while cooking serious conversation cannot handle.",
    speak: {
      text: "I can discuss this after dinner.",
      hiDeva: "मैं dinner के बाद इस पर बात कर सकती हूँ।",
      hiLatn: "Main dinner ke baad is par baat kar sakti hoon.",
    },
    tags: ["time-prepositions", "negative-sentence", "confidence", "family"],
  },
  {
    id: "repair-misunderstanding",
    moduleId: "conflict-and-boundaries",
    title: "Repair A Misunderstanding",
    overview: "You will practice clarifying what you meant without sounding defensive.",
    skipOverview: ["Naming the misunderstanding", "Restating your intention", "Inviting calm discussion"],
    main: {
      text: "I think my words sounded harsh, but my intention was to explain the problem clearly.",
      hiDeva: "मुझे लगता है मेरे words harsh लगे, लेकिन मेरा intention problem clearly explain करना था।",
      hiLatn: "Mujhe lagta hai mere words harsh lage, lekin mera intention problem clearly explain karna tha.",
    },
    support: {
      text: "Let me say it again in a calmer way.",
      hiDeva: "मैं इसे फिर से calmer way में कहती हूँ।",
      hiLatn: "Main ise phir se calmer way mein kehti hoon.",
    },
    keyPhrase: "but",
    keyOptions: ["but", "because", "until"],
    keyExplanation: {
      hiDeva: "'But' harsh sound और real intention को अलग करता है।",
      hiLatn: "'But' harsh sound aur real intention ko alag karta hai.",
    },
    incorrect: "My words harsh sounded but intention explain problem clearly.",
    wrong: "I think words sounded harsh but intention was problem explain clear.",
    speak: {
      text: "Let me say it again in a calmer way.",
      hiDeva: "मैं इसे फिर से calmer way में कहती हूँ।",
      hiLatn: "Main ise phir se calmer way mein kehti hoon.",
    },
    tags: ["clarification", "polite-disagreement", "confidence", "problem-solving"],
  },
  {
    id: "express-need-without-blame",
    moduleId: "conflict-and-boundaries",
    title: "Express A Need Without Blame",
    overview: "You will practice asking for support by focusing on your need, not blame.",
    skipOverview: ["Using I-statements", "Naming the need", "Making a concrete request"],
    main: {
      text: "I feel overwhelmed when plans change suddenly, so I need earlier information whenever possible.",
      hiDeva: "Plans अचानक change होते हैं तो मैं overwhelmed feel करती हूँ, इसलिए possible हो तो मुझे earlier information चाहिए।",
      hiLatn: "Plans achanak change hote hain to main overwhelmed feel karti hoon, isliye possible ho to mujhe earlier information chahiye.",
    },
    support: {
      text: "This will help me arrange the home schedule without stress.",
      hiDeva: "इससे मुझे home schedule बिना stress arrange करने में help मिलेगी।",
      hiLatn: "Isse mujhe home schedule bina stress arrange karne mein help milegi.",
    },
    keyPhrase: "so",
    keyOptions: ["so", "although", "before"],
    keyExplanation: {
      hiDeva: "'So I need...' feeling को request से जोड़ता है।",
      hiLatn: "'So I need...' feeling ko request se jodta hai.",
    },
    incorrect: "I overwhelmed when plans change suddenly so need earlier information possible.",
    wrong: "Plans change suddenly so earlier information need overwhelmed possible.",
    speak: {
      text: "I need earlier information whenever possible.",
      hiDeva: "Possible हो तो मुझे earlier information चाहिए।",
      hiLatn: "Possible ho to mujhe earlier information chahiye.",
    },
    tags: ["confidence", "polite-request", "reason-connector", "planning"],
  },
  {
    id: "narrate-challenge-and-solution",
    moduleId: "storytelling-and-opinions",
    title: "Narrate A Challenge And Solution",
    overview: "You will practice telling a short story with problem, action, and result.",
    skipOverview: ["Starting with the challenge", "Explaining your action", "Ending with the result"],
    main: {
      text: "Last month our routine became difficult, so I made a simple chart and the mornings became calmer.",
      hiDeva: "Last month हमारा routine difficult हो गया था, इसलिए मैंने simple chart बनाया और mornings calmer हो गईं।",
      hiLatn: "Last month hamara routine difficult ho gaya tha, isliye maine simple chart banaya aur mornings calmer ho gayin.",
    },
    support: {
      text: "It taught me that small systems can reduce daily stress.",
      hiDeva: "इससे मैंने सीखा कि small systems daily stress कम कर सकते हैं।",
      hiLatn: "Isse maine seekha ki small systems daily stress kam kar sakte hain.",
    },
    keyPhrase: "so",
    keyOptions: ["so", "although", "unless"],
    keyExplanation: {
      hiDeva: "'So' challenge के बाद solution connect करता है।",
      hiLatn: "'So' challenge ke baad solution connect karta hai.",
    },
    incorrect: "Last month routine difficult so I made chart mornings calmer.",
    wrong: "Routine difficult last month chart made so mornings became calm.",
    speak: {
      text: "Small systems can reduce daily stress.",
      hiDeva: "Small systems daily stress कम कर सकते हैं।",
      hiLatn: "Small systems daily stress kam kar sakte hain.",
    },
    tags: ["summary", "reason-connector", "daily-routine", "confidence"],
  },
  {
    id: "explain-why-opinion-changed",
    moduleId: "storytelling-and-opinions",
    title: "Explain Why Your Opinion Changed",
    overview: "You will practice changing your opinion without sounding unsure.",
    skipOverview: ["Naming your old view", "Explaining new information", "Giving your current view"],
    main: {
      text: "Earlier I thought online classes were not useful, but I changed my opinion after seeing her progress.",
      hiDeva: "पहले मुझे लगता था online classes useful नहीं हैं, लेकिन उसकी progress देखकर मेरी opinion change हुई।",
      hiLatn: "Pehle mujhe lagta tha online classes useful nahi hain, lekin uski progress dekhkar meri opinion change hui.",
    },
    support: {
      text: "Now I feel they can help if the routine is balanced.",
      hiDeva: "अब मुझे लगता है कि routine balanced हो तो वे help कर सकती हैं।",
      hiLatn: "Ab mujhe lagta hai ki routine balanced ho to ve help kar sakti hain.",
    },
    keyPhrase: "after",
    keyOptions: ["after", "before", "because of"],
    keyExplanation: {
      hiDeva: "'After seeing her progress' बताता है opinion कब और क्यों बदली।",
      hiLatn: "'After seeing her progress' batata hai opinion kab aur kyun badli.",
    },
    incorrect: "Earlier I thought online classes not useful but changed opinion after seeing progress.",
    wrong: "I changed opinion useful online classes after progress seeing but earlier.",
    speak: {
      text: "I changed my opinion after seeing her progress.",
      hiDeva: "उसकी progress देखकर मेरी opinion change हुई।",
      hiLatn: "Uski progress dekhkar meri opinion change hui.",
    },
    tags: ["preference", "contrast-connector", "school-family", "summary"],
  },
  {
    id: "compare-past-and-present",
    moduleId: "storytelling-and-opinions",
    title: "Compare Past And Present",
    overview: "You will practice comparing how things were before and how they are now.",
    skipOverview: ["Using earlier and now", "Naming the change", "Explaining the reason"],
    main: {
      text: "Earlier I avoided speaking English outside, but now I try one small sentence whenever I get a chance.",
      hiDeva: "पहले मैं बाहर English बोलने से बचती थी, लेकिन अब मौका मिलने पर एक small sentence try करती हूँ।",
      hiLatn: "Pehle main bahar English bolne se bachti thi, lekin ab mauka milne par ek small sentence try karti hoon.",
    },
    support: {
      text: "This habit has made me less nervous in public places.",
      hiDeva: "इस habit से मैं public places में कम nervous हुई हूँ।",
      hiLatn: "Is habit se main public places mein kam nervous hui hoon.",
    },
    keyPhrase: "whenever",
    keyOptions: ["whenever", "whatever", "wherever"],
    keyExplanation: {
      hiDeva: "'Whenever I get a chance' repeated opportunity बताता है।",
      hiLatn: "'Whenever I get a chance' repeated opportunity batata hai.",
    },
    incorrect: "Earlier avoided speaking English outside but now try one sentence chance.",
    wrong: "Now I try small sentence whenever chance get earlier avoided English.",
    speak: {
      text: "Now I try one small sentence whenever I get a chance.",
      hiDeva: "अब मौका मिलने पर मैं एक small sentence try करती हूँ।",
      hiLatn: "Ab mauka milne par main ek small sentence try karti hoon.",
    },
    tags: ["confidence", "small-talk", "present-perfect", "contrast-connector"],
  },
  {
    id: "describe-proud-moment",
    moduleId: "storytelling-and-opinions",
    title: "Describe A Proud Moment",
    overview: "You will practice describing a proud moment with details and feeling.",
    skipOverview: ["Naming the event", "Saying what you did", "Explaining why it mattered"],
    main: {
      text: "I felt proud when I handled the school meeting in English without asking anyone to speak for me.",
      hiDeva: "मुझे proud feel हुआ जब मैंने school meeting English में handle की और किसी से मेरे लिए बोलने को नहीं कहा।",
      hiLatn: "Mujhe proud feel hua jab maine school meeting English mein handle ki aur kisi se mere liye bolne ko nahi kaha.",
    },
    support: {
      text: "It showed me that practice is slowly becoming confidence.",
      hiDeva: "इससे मुझे लगा कि practice धीरे-धीरे confidence बन रही है।",
      hiLatn: "Isse mujhe laga ki practice dheere-dheere confidence ban rahi hai.",
    },
    keyPhrase: "without",
    keyOptions: ["without", "within", "until"],
    keyExplanation: {
      hiDeva: "'Without asking anyone...' बताता है कि आपने खुद बोलकर काम किया।",
      hiLatn: "'Without asking anyone...' batata hai ki aapne khud bolkar kaam kiya.",
    },
    incorrect: "I felt proud when handled school meeting English without asking anyone speak me.",
    wrong: "I proud felt school meeting handled without anyone speak for me English.",
    speak: {
      text: "Practice is slowly becoming confidence.",
      hiDeva: "Practice धीरे-धीरे confidence बन रही है।",
      hiLatn: "Practice dheere-dheere confidence ban rahi hai.",
    },
    tags: ["confidence", "school-family", "summary", "formal-follow-up"],
  },
  {
    id: "give-balanced-opinion",
    moduleId: "storytelling-and-opinions",
    title: "Give A Balanced Opinion",
    overview: "You will practice giving an opinion with both positives and concerns.",
    skipOverview: ["Naming the positive side", "Adding a concern", "Giving your final view"],
    main: {
      text: "This plan has some good points, although I still worry about the cost and timing.",
      hiDeva: "इस plan में कुछ good points हैं, हालांकि मुझे अभी भी cost और timing की चिंता है।",
      hiLatn: "Is plan mein kuch good points hain, halaanki mujhe abhi bhi cost aur timing ki chinta hai.",
    },
    support: {
      text: "I would support it if we make the budget clearer first.",
      hiDeva: "अगर हम पहले budget clear कर दें, तो मैं इसे support करूँगी।",
      hiLatn: "Agar hum pehle budget clear kar dein, to main ise support karungi.",
    },
    keyPhrase: "although",
    keyOptions: ["although", "because", "until"],
    keyExplanation: {
      hiDeva: "'Although' positive point और concern को balance करता है।",
      hiLatn: "'Although' positive point aur concern ko balance karta hai.",
    },
    incorrect: "This plan has good points although still worry cost timing.",
    wrong: "Although plan good points cost timing still worry has.",
    speak: {
      text: "I still worry about the cost and timing.",
      hiDeva: "मुझे अभी भी cost और timing की चिंता है।",
      hiLatn: "Mujhe abhi bhi cost aur timing ki chinta hai.",
    },
    tags: ["preference", "contrast-connector", "decision-discussion", "polite-disagreement"],
  },
  {
    id: "introduce-topic-in-meeting",
    moduleId: "public-speaking-and-groups",
    title: "Introduce A Topic In A Meeting",
    overview: "You will practice opening a group discussion with a clear topic.",
    skipOverview: ["Naming the topic", "Explaining why it matters", "Inviting discussion"],
    main: {
      text: "I would like to discuss the parking issue because it is affecting both safety and daily convenience.",
      hiDeva: "मैं parking issue discuss करना चाहती हूँ क्योंकि यह safety और daily convenience दोनों को affect कर रहा है।",
      hiLatn: "Main parking issue discuss karna chahti hoon kyunki yeh safety aur daily convenience dono ko affect kar raha hai.",
    },
    support: {
      text: "Let us first list the main problems before deciding a solution.",
      hiDeva: "Solution decide करने से पहले main problems list कर लेते हैं।",
      hiLatn: "Solution decide karne se pehle main problems list kar lete hain.",
    },
    keyPhrase: "because",
    keyOptions: ["because", "although", "before"],
    keyExplanation: {
      hiDeva: "'Because' topic importance explain करता है।",
      hiLatn: "'Because' topic importance explain karta hai.",
    },
    incorrect: "I like discuss parking issue because affecting safety daily convenience.",
    wrong: "Parking issue discuss because safety convenience affecting would like.",
    speak: {
      text: "I would like to discuss the parking issue.",
      hiDeva: "मैं parking issue discuss करना चाहती हूँ।",
      hiLatn: "Main parking issue discuss karna chahti hoon.",
    },
    tags: ["summary", "reason-connector", "problem-reporting", "decision-discussion"],
  },
  {
    id: "support-someone-else-point",
    moduleId: "public-speaking-and-groups",
    title: "Support Someone Else's Point",
    overview: "You will practice adding support to another person's point in a group.",
    skipOverview: ["Agreeing politely", "Adding evidence", "Keeping your point short"],
    main: {
      text: "I agree with her point, and I would like to add one example from our building.",
      hiDeva: "मैं उनकी बात से agree करती हूँ, और अपनी building से एक example add करना चाहती हूँ।",
      hiLatn: "Main unki baat se agree karti hoon, aur apni building se ek example add karna chahti hoon.",
    },
    support: {
      text: "The same issue happened near our staircase last week.",
      hiDeva: "Same issue last week हमारी staircase के पास हुआ था।",
      hiLatn: "Same issue last week hamari staircase ke paas hua tha.",
    },
    keyPhrase: "and",
    keyOptions: ["and", "but", "unless"],
    keyExplanation: {
      hiDeva: "'And' agreement के बाद extra example जोड़ता है।",
      hiLatn: "'And' agreement ke baad extra example jodta hai.",
    },
    incorrect: "I agree her point and like add one example building.",
    wrong: "I would like add example agree with her point building.",
    speak: {
      text: "I would like to add one example.",
      hiDeva: "मैं एक example add करना चाहती हूँ।",
      hiLatn: "Main ek example add karna chahti hoon.",
    },
    tags: ["summary", "polite-disagreement", "confidence", "problem-reporting"],
  },
  {
    id: "ask-group-to-decide",
    moduleId: "public-speaking-and-groups",
    title: "Ask A Group To Decide",
    overview: "You will practice moving a discussion toward a decision.",
    skipOverview: ["Summarizing options", "Asking for a decision", "Checking agreement"],
    main: {
      text: "We have discussed three options, so can we decide which one is practical for this month?",
      hiDeva: "हमने तीन options discuss किए हैं, इसलिए क्या हम decide कर सकते हैं कि इस month कौन सा practical है?",
      hiLatn: "Humne teen options discuss kiye hain, isliye kya hum decide kar sakte hain ki is month kaunsa practical hai?",
    },
    support: {
      text: "If needed, we can review the decision again next month.",
      hiDeva: "ज़रूरत हो तो हम decision next month फिर review कर सकते हैं।",
      hiLatn: "Zaroorat ho to hum decision next month phir review kar sakte hain.",
    },
    keyPhrase: "so",
    keyOptions: ["so", "although", "before"],
    keyExplanation: {
      hiDeva: "'So can we decide...' discussion को decision की तरफ ले जाता है।",
      hiLatn: "'So can we decide...' discussion ko decision ki taraf le jaata hai.",
    },
    incorrect: "We discussed three options so decide which practical this month?",
    wrong: "Can decide which one practical three options discussed this month?",
    speak: {
      text: "Can we decide which one is practical?",
      hiDeva: "क्या हम decide कर सकते हैं कि कौन सा practical है?",
      hiLatn: "Kya hum decide kar sakte hain ki kaunsa practical hai?",
    },
    tags: ["decision-discussion", "summary", "question-formation", "planning"],
  },
  {
    id: "summarize-mixed-opinions",
    moduleId: "public-speaking-and-groups",
    title: "Summarize Mixed Opinions",
    overview: "You will practice summarizing different opinions fairly.",
    skipOverview: ["Naming both sides", "Avoiding judgment", "Suggesting a middle path"],
    main: {
      text: "Some members prefer a quick solution, while others want more time to compare the costs.",
      hiDeva: "कुछ members quick solution prefer करते हैं, जबकि others costs compare करने के लिए more time चाहते हैं।",
      hiLatn: "Kuch members quick solution prefer karte hain, jabki others costs compare karne ke liye more time chahte hain.",
    },
    support: {
      text: "A one-week deadline may respect both concerns.",
      hiDeva: "One-week deadline दोनों concerns को respect कर सकती है।",
      hiLatn: "One-week deadline dono concerns ko respect kar sakti hai.",
    },
    keyPhrase: "while",
    keyOptions: ["while", "because", "after"],
    keyExplanation: {
      hiDeva: "'While' दो अलग opinions को fair तरीके से दिखाता है।",
      hiLatn: "'While' do alag opinions ko fair tareeke se dikhata hai.",
    },
    incorrect: "Some members prefer quick solution while others more time compare costs.",
    wrong: "While some members quick solution others want compare costs time.",
    speak: {
      text: "Some members prefer a quick solution.",
      hiDeva: "कुछ members quick solution prefer करते हैं।",
      hiLatn: "Kuch members quick solution prefer karte hain.",
    },
    tags: ["summary", "contrast-connector", "decision-discussion", "preference"],
  },
  {
    id: "close-group-discussion",
    moduleId: "public-speaking-and-groups",
    title: "Close A Group Discussion",
    overview: "You will practice ending a group discussion with clear next steps.",
    skipOverview: ["Thanking the group", "Naming the action", "Confirming timeline"],
    main: {
      text: "Thank you for sharing your views; I will note the final points and send the summary tonight.",
      hiDeva: "अपने views share करने के लिए thank you; मैं final points note करके tonight summary भेज दूँगी।",
      hiLatn: "Apne views share karne ke liye thank you; main final points note karke tonight summary bhej dungi.",
    },
    support: {
      text: "Please message me if I miss any important detail.",
      hiDeva: "अगर मुझसे कोई important detail miss हो जाए तो please message कीजिए।",
      hiLatn: "Agar mujhse koi important detail miss ho jaaye to please message kijiye.",
    },
    keyPhrase: "and",
    keyOptions: ["and", "but", "unless"],
    keyExplanation: {
      hiDeva: "'And' note करने और summary भेजने के दो actions connect करता है।",
      hiLatn: "'And' note karne aur summary bhejne ke do actions connect karta hai.",
    },
    incorrect: "Thank you sharing views I note final points send summary tonight.",
    wrong: "I will note final points summary tonight send views sharing thank you.",
    speak: {
      text: "I will send the summary tonight.",
      hiDeva: "मैं tonight summary भेज दूँगी।",
      hiLatn: "Main tonight summary bhej dungi.",
    },
    tags: ["summary", "formal-follow-up", "message", "future-plan"],
  },
  {
    id: "handle-difficult-phone-negotiation",
    moduleId: "advanced-fluency-mix",
    title: "Handle A Difficult Phone Negotiation",
    overview: "You will practice staying calm during a complicated phone negotiation.",
    skipOverview: ["Restating the issue", "Requesting a fair option", "Asking for written confirmation"],
    main: {
      text: "I understand the policy, but I am requesting an exception because the delay happened from your side.",
      hiDeva: "मैं policy समझती हूँ, लेकिन exception request कर रही हूँ क्योंकि delay आपकी side से हुआ।",
      hiLatn: "Main policy samajhti hoon, lekin exception request kar rahi hoon kyunki delay aapki side se hua.",
    },
    support: {
      text: "Please confirm the final decision by message after this call.",
      hiDeva: "इस call के बाद final decision message से confirm कर दीजिए।",
      hiLatn: "Is call ke baad final decision message se confirm kar dijiye.",
    },
    keyPhrase: "because",
    keyOptions: ["because", "although", "unless"],
    keyExplanation: {
      hiDeva: "'Because' exception request का factual reason देता है।",
      hiLatn: "'Because' exception request ka factual reason deta hai.",
    },
    incorrect: "I understand policy but requesting exception because delay your side happened.",
    wrong: "Exception requesting because policy understand delay happened your side.",
    speak: {
      text: "Please confirm the final decision by message.",
      hiDeva: "कृपया final decision message से confirm कीजिए।",
      hiLatn: "Please final decision message se confirm kijiye.",
    },
    tags: ["phone-call", "formal-follow-up", "polite-request", "problem-solving"],
  },
  {
    id: "explain-complicated-sequence",
    moduleId: "advanced-fluency-mix",
    title: "Explain A Complicated Sequence",
    overview: "You will practice explaining a multi-step problem in the correct order.",
    skipOverview: ["Starting at the beginning", "Using after and then", "Ending with current status"],
    main: {
      text: "After I updated the app, the payment failed, and then the order disappeared from my account.",
      hiDeva: "App update करने के बाद payment failed हुआ, और फिर order मेरे account से disappear हो गया।",
      hiLatn: "App update karne ke baad payment failed hua, aur phir order mere account se disappear ho gaya.",
    },
    support: {
      text: "Now I need to know whether the amount will be refunded automatically.",
      hiDeva: "अब मुझे जानना है कि amount automatically refund होगा या नहीं।",
      hiLatn: "Ab mujhe jaanna hai ki amount automatically refund hoga ya nahi.",
    },
    keyPhrase: "After",
    keyOptions: ["After", "Before", "Although"],
    keyExplanation: {
      hiDeva: "'After' sequence की शुरुआत clear करता है।",
      hiLatn: "'After' sequence ki shuruaat clear karta hai.",
    },
    incorrect: "After updated app payment failed then order disappeared account.",
    wrong: "Payment failed after app updated and order disappeared then account.",
    speak: {
      text: "The order disappeared from my account.",
      hiDeva: "Order मेरे account से disappear हो गया।",
      hiLatn: "Order mere account se disappear ho gaya.",
    },
    tags: ["problem-reporting", "time-prepositions", "clarification", "problem-solving"],
  },
  {
    id: "make-conditional-request",
    moduleId: "advanced-fluency-mix",
    title: "Make A Conditional Request",
    overview: "You will practice making a request that depends on a condition.",
    skipOverview: ["Setting the condition", "Making the request", "Keeping it polite"],
    main: {
      text: "If the appointment is delayed again, could you please arrange a phone consultation instead?",
      hiDeva: "अगर appointment फिर delay हो, तो क्या आप please phone consultation arrange कर सकते हैं?",
      hiLatn: "Agar appointment phir delay ho, to kya aap please phone consultation arrange kar sakte hain?",
    },
    support: {
      text: "It will save travel time and still help me get advice.",
      hiDeva: "इससे travel time बचेगा और फिर भी advice मिल जाएगी।",
      hiLatn: "Isse travel time bachega aur phir bhi advice mil jaayegi.",
    },
    keyPhrase: "If",
    keyOptions: ["If", "Although", "Before"],
    keyExplanation: {
      hiDeva: "'If' condition रखता है: appointment delay हो तो phone consultation चाहिए।",
      hiLatn: "'If' condition rakhta hai: appointment delay ho to phone consultation chahiye.",
    },
    incorrect: "If appointment delayed again could arrange phone consultation instead?",
    wrong: "Could phone consultation arrange if delayed appointment instead again?",
    speak: {
      text: "Could you please arrange a phone consultation instead?",
      hiDeva: "क्या आप please phone consultation arrange कर सकते हैं?",
      hiLatn: "Kya aap please phone consultation arrange kar sakte hain?",
    },
    tags: ["appointment", "polite-request", "advice-question", "time-prepositions"],
  },
  {
    id: "clarify-before-committing",
    moduleId: "advanced-fluency-mix",
    title: "Clarify Before Committing",
    overview: "You will practice asking questions before agreeing to something.",
    skipOverview: ["Saying you need clarity", "Asking about responsibility", "Delaying commitment politely"],
    main: {
      text: "Before I agree, I need to understand exactly what work I will be responsible for.",
      hiDeva: "Agree करने से पहले मुझे exactly समझना है कि मैं किस work की responsible रहूँगी।",
      hiLatn: "Agree karne se pehle mujhe exactly samajhna hai ki main kis work ki responsible rahungi.",
    },
    support: {
      text: "Once the responsibility is clear, I can give you a proper answer.",
      hiDeva: "Responsibility clear होने के बाद मैं proper answer दे सकती हूँ।",
      hiLatn: "Responsibility clear hone ke baad main proper answer de sakti hoon.",
    },
    keyPhrase: "Before",
    keyOptions: ["Before", "After", "Because"],
    keyExplanation: {
      hiDeva: "'Before I agree' commitment से पहले clarity माँगता है।",
      hiLatn: "'Before I agree' commitment se pehle clarity maangta hai.",
    },
    incorrect: "Before agree I need understand exactly what work responsible.",
    wrong: "I need understand work responsible before agree exactly.",
    speak: {
      text: "I need to understand the responsibility clearly.",
      hiDeva: "मुझे responsibility clearly समझनी है।",
      hiLatn: "Mujhe responsibility clearly samajhni hai.",
    },
    tags: ["clarification", "decision-discussion", "polite-request", "confidence"],
  },
  {
    id: "reflect-on-learning-progress",
    moduleId: "advanced-fluency-mix",
    title: "Reflect On Learning Progress",
    overview: "You will practice reflecting on your English learning progress with confidence.",
    skipOverview: ["Naming the progress", "Explaining what helped", "Setting the next goal"],
    main: {
      text: "I still make mistakes, but I can now explain my thoughts more clearly than before.",
      hiDeva: "मैं अभी भी mistakes करती हूँ, लेकिन अब अपने thoughts पहले से ज़्यादा clearly explain कर सकती हूँ।",
      hiLatn: "Main abhi bhi mistakes karti hoon, lekin ab apne thoughts pehle se zyada clearly explain kar sakti hoon.",
    },
    support: {
      text: "My next goal is to speak for two minutes without stopping.",
      hiDeva: "मेरा next goal है कि मैं बिना रुके two minutes बोलूँ।",
      hiLatn: "Mera next goal hai ki main bina ruke two minutes bolun.",
    },
    keyPhrase: "but",
    keyOptions: ["but", "because", "until"],
    keyExplanation: {
      hiDeva: "'But' mistake के बाद progress को confidently दिखाता है।",
      hiLatn: "'But' mistake ke baad progress ko confidently dikhata hai.",
    },
    incorrect: "I still make mistakes but now explain thoughts more clearly before.",
    wrong: "Mistakes still make but thoughts explain clearly than before now.",
    speak: {
      text: "I can explain my thoughts more clearly than before.",
      hiDeva: "मैं अपने thoughts पहले से ज़्यादा clearly explain कर सकती हूँ।",
      hiLatn: "Main apne thoughts pehle se zyada clearly explain kar sakti hoon.",
    },
    tags: ["confidence", "summary", "contrast-connector", "future-plan"],
  },
];

export const advancedLessons: Lesson[] = advancedLessonSpecs.map(createAdvancedLesson);

export const advancedLessonSkillProfiles: Record<string, LessonSkillTag[]> = Object.fromEntries(
  advancedLessonSpecs.map((lesson) => [lesson.id, lesson.tags]),
);
