import type { LearningModule } from "@/src/types/content";
import { advancedModules } from "@/src/content/advancedCurriculum";
import { expandedModules } from "@/src/content/expandedCurriculum";

export const modules: LearningModule[] = [
  {
    id: "first-sentences",
    title: "First English Sentences",
    level: "Beginner",
    stage: 1,
    skillFocus: "Say one complete English sentence without fear.",
    challenge: "Short greetings, names, and polite words.",
    overview: "Start with greetings, your name, polite words, and simple confidence-building lines.",
    lessonIds: ["greetings-intro", "polite-help"],
  },
  {
    id: "home-family",
    title: "Home And Family",
    level: "Beginner",
    stage: 2,
    skillFocus: "Talk about people, home routines, and small needs.",
    challenge: "Add family words, time words, and simple requests.",
    overview: "Practice talking about family, daily routines, and simple needs at home.",
    lessonIds: ["family-routine", "home-needs", "guest-at-home", "child-school-day"],
  },
  {
    id: "shopping-directions",
    title: "Shopping And Directions",
    level: "Beginner",
    stage: 3,
    skillFocus: "Ask practical questions outside the home.",
    challenge: "Use question order for price, place, and transport.",
    overview: "Learn useful lines for prices, shops, local transport, and asking where something is.",
    lessonIds: ["shopping-price", "take-local-transport"],
  },
  {
    id: "community-errands",
    title: "Community Errands",
    level: "Beginner",
    stage: 4,
    skillFocus: "Explain basic needs to service people.",
    challenge: "Describe symptoms, repairs, bank help, and society issues.",
    overview: "Practice simple English for the clinic, chemist, society office, bank, and repair calls.",
    lessonIds: ["clinic-medicine", "society-office-help", "bank-atm-help", "repair-service-call"],
  },
  {
    id: "daily-conversations",
    title: "Daily Conversations",
    level: "Beginner Plus",
    stage: 5,
    skillFocus: "Hold a short back-and-forth conversation.",
    challenge: "Combine greeting, reason, timing, and one follow-up.",
    overview: "Build slightly longer conversations for phone calls, neighbors, appointments, and explaining small problems.",
    lessonIds: ["phone-call-basics", "neighbor-small-talk", "appointment-timing", "explain-small-problem"],
  },
  {
    id: "everyday-problem-solving",
    title: "Everyday Problem Solving",
    level: "Beginner Plus",
    stage: 6,
    skillFocus: "Explain changes, delays, and problems clearly.",
    challenge: "Use because, before, after, and polite follow-up.",
    overview:
      "Move into longer, more natural English for planning, explaining delays, community issues, and school meetings.",
    lessonIds: [
      "plan-family-event",
      "explain-delay-change",
      "community-issue-follow-up",
      "school-meeting-feedback",
    ],
  },
  {
    id: "confident-community-conversations",
    title: "Confident Community Conversations",
    level: "Intermediate",
    stage: 7,
    skillFocus: "Speak in connected sentences with confidence.",
    challenge: "Disagree politely, clarify misunderstandings, and summarize.",
    overview:
      "Practice connected English for polite disagreement, preferences, misunderstandings, follow-up questions, and problem summaries.",
    lessonIds: [
      "polite-disagreement-preference",
      "handle-misunderstanding-follow-up",
      "summarize-service-problem",
      "community-decision-discussion",
    ],
  },
  ...expandedModules,
  ...advancedModules,
];
