import type { Scenario } from "@/src/types/content";

export const scenarios: Scenario[] = [
  {
    id: "introductions",
    title: "Introductions",
    icon: "👋",
    difficulty: "Easy",
    goal: "Say hello, share your name, and answer one simple question.",
    starter: "Hello, I am your speaking coach. What is your name?",
    suggestedReplies: ["My name is...", "I live in...", "Nice to meet you."],
  },
  {
    id: "shopping",
    title: "Shopping",
    icon: "🛍️",
    difficulty: "Guided",
    goal: "Ask for an item, price, and quantity at a shop.",
    starter: "Welcome. What would you like to buy today?",
    suggestedReplies: ["I want...", "How much is this?", "Please give me one kilo."],
  },
  {
    id: "parent-teacher",
    title: "Parent-Teacher",
    icon: "🏫",
    difficulty: "Guided",
    goal: "Ask about your child's homework, progress, and school day in simple English.",
    starter: "Good morning. How can I help you today?",
    suggestedReplies: ["How is my child doing?", "Does she complete homework?", "Please tell me what to practice at home."],
  },
  {
    id: "travel",
    title: "Travel",
    icon: "🚕",
    difficulty: "Easy",
    goal: "Ask for directions, timings, and local transport help.",
    starter: "Where do you want to go?",
    suggestedReplies: ["I want to go to...", "How far is it?", "Please stop here."],
  },
  {
    id: "customer-service",
    title: "Customer Service",
    icon: "☎️",
    difficulty: "Natural",
    goal: "Explain a simple problem and ask for help.",
    starter: "Hello, customer support. What problem are you facing?",
    suggestedReplies: ["I need help.", "My order is late.", "Can you check, please?"],
  },
  {
    id: "interview",
    title: "Interview",
    icon: "💬",
    difficulty: "Guided",
    goal: "Practice a simple self-introduction for an interview.",
    starter: "Please tell me about yourself.",
    suggestedReplies: ["My name is...", "I am a homemaker.", "I am learning English."],
  },
  {
    id: "office-call",
    title: "Office Call",
    icon: "📞",
    difficulty: "Natural",
    goal: "Speak politely to a manager or office staff.",
    starter: "Hello, this is the office. How may I help you?",
    suggestedReplies: ["May I speak to...", "I have one question.", "Thank you for your help."],
  },
  {
    id: "small-talk",
    title: "Small Talk",
    icon: "☕",
    difficulty: "Easy",
    goal: "Talk with a neighbor or guest using friendly sentences.",
    starter: "Hi, how are you today?",
    suggestedReplies: ["I am fine.", "Would you like tea?", "Please come in."],
  },
  {
    id: "guest-at-home",
    title: "Guest At Home",
    icon: "🏠",
    difficulty: "Easy",
    goal: "Welcome a guest, offer tea or water, and speak politely at home.",
    starter: "Namaste, I have come to visit your family.",
    suggestedReplies: ["Please come in.", "Would you like some tea?", "Please sit here."],
  },
  {
    id: "family-routine",
    title: "Family Routine",
    icon: "🍽️",
    difficulty: "Easy",
    goal: "Talk about cooking, breakfast, children, and simple daily work at home.",
    starter: "Tell me about your morning at home.",
    suggestedReplies: ["I cook breakfast in the morning.", "I pack lunch for my family.", "My children go to school."],
  },
  {
    id: "child-homework",
    title: "Child Homework",
    icon: "📚",
    difficulty: "Guided",
    goal: "Ask a child about school and give one gentle homework reminder.",
    starter: "Mummy, I came back from school.",
    suggestedReplies: ["How was school today?", "Do you have homework?", "Please finish your homework first."],
  },
  {
    id: "home-help",
    title: "Home Help",
    icon: "🧺",
    difficulty: "Guided",
    goal: "Ask a family member for help with small home tasks in polite English.",
    starter: "I am here. Do you need any help at home?",
    suggestedReplies: ["Can you help me in the kitchen?", "The milk is finished.", "Please bring some vegetables."],
  },
  {
    id: "clinic-chemist",
    title: "Clinic And Chemist",
    icon: "💊",
    difficulty: "Guided",
    goal: "Tell a symptom, ask about medicine, and check if it is for a child or adult.",
    starter: "Hello, please tell me what problem you are facing.",
    suggestedReplies: ["My son has fever.", "How should I give this medicine?", "Is this medicine for children?"],
  },
  {
    id: "society-office",
    title: "Society Office",
    icon: "🏢",
    difficulty: "Guided",
    goal: "Ask about maintenance, report a water problem, and request help politely.",
    starter: "Good morning. How can the society office help you?",
    suggestedReplies: ["Is my maintenance bill due?", "There is no water at home.", "Please send someone today."],
  },
  {
    id: "bank-atm",
    title: "Bank And ATM",
    icon: "🏦",
    difficulty: "Natural",
    goal: "Ask for the right counter, explain an ATM problem, and request form help.",
    starter: "Welcome to the bank. What help do you need?",
    suggestedReplies: ["Which counter is for cash deposit?", "The ATM is not working.", "Can you help me with this form?"],
  },
  {
    id: "repair-service",
    title: "Repair Service",
    icon: "🔧",
    difficulty: "Guided",
    goal: "Call a repair person, explain a home problem, and agree on a visit time.",
    starter: "Hello, this is repair service. What is the problem?",
    suggestedReplies: ["The fan is not working.", "When can you come?", "I will send my address on WhatsApp."],
  },
  {
    id: "appointment-call",
    title: "Appointment Call",
    icon: "📅",
    difficulty: "Guided",
    goal: "Ask for an available time, say when you can come, and confirm the appointment.",
    starter: "Hello, please tell me which appointment time you need.",
    suggestedReplies: ["What time is available?", "I can come tomorrow morning.", "Okay, I will come at ten."],
  },
  {
    id: "explain-problem",
    title: "Explain A Problem",
    icon: "💡",
    difficulty: "Natural",
    goal: "Explain one small home or service problem and ask what to do next.",
    starter: "Tell me the problem. I will help you.",
    suggestedReplies: ["There is a small problem.", "The light is not working.", "What should I do now?"],
  },
  {
    id: "clear-misunderstanding",
    title: "Clear A Misunderstanding",
    icon: "📝",
    difficulty: "Natural",
    goal: "Explain that you may have misunderstood, ask for clarification, and check the next step.",
    starter: "I sent the instructions yesterday. Which part is not clear?",
    suggestedReplies: [
      "I may have misunderstood the timing.",
      "Could you explain the last step again?",
      "Should I wait for your message?",
    ],
  },
  {
    id: "society-decision",
    title: "Society Decision",
    icon: "🏘️",
    difficulty: "Natural",
    goal: "Share a balanced opinion, ask a follow-up question, and summarize the decision.",
    starter: "We need to decide about the repair work today. What do you think?",
    suggestedReplies: [
      "I agree that the repair is important.",
      "Can you share two estimates?",
      "Let me summarize the decision for everyone.",
    ],
  },
];
